### ISSUE TITLE
Meta: So many specs but how to keep track?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-extensions#104]
It's hard to keep track of all the WebRTC **web** specs. In lieu of a living standard (like most WHATWG specs), we're stuck with WebRTC 1.0, stats, media capture and then dozens of separate extension specs. Honestly, I have no idea how many there are, that may even be partially implemented, I never heard of before (okay probably not that many, but still). Hence, it would be great if there were an overview of all WebRTC **web** specs and their status.

Note that I'm not talking about cluster 238 or any other IETF specs.

**Comment by jan-ivar** [comment]
That list looks reasonably up to date, except for https://w3c.github.io/mediacapture-handle/

**Comment by lgrahl** [comment]
Handsome! Can we pin those somewhere more accessible, like the readme of webrtc-pc which has this [handy section called "useful links"](https://github.com/w3c/webrtc-pc#useful-links)?

**Comment by alvestrand** [comment]
I have a metarepository here:
https://github.com/alvestrand/webrtc-specs

**Comment by aboba** [comment]
Closing unless there is an actionable proposal for the WebRTC-Extensions specification.
