### ISSUE TITLE
maxFramerate probably should not be allowed in addTransceiver/setParameters for audio senders

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-extensions#107]
maxFramerate appears to be intended as a video-only parameter, so we probably ought to throw an error in the audio cases of addTransceiver and setParameters.

**Comment by aboba** [comment]
Feedback from June 19, 2022 WEBRTC WG Virtual Interim: "Ready for PR"

**Comment by aboba** [comment]
maxFramerate has been moved to WebRTC-PC, so the issue has been refiled as https://github.com/w3c/webrtc-pc/issues/2815
