### ISSUE TITLE
RTCRtpEncodingParameters.maxFramerate and other extensions "mature"?

### ISSUE THREAD

**Issue by hamishwillee** [w3c/webrtc-extensions#108]
I tried to add this specification to  w3c/browser-specs (https://github.com/w3c/browser-specs/pull/605) in order to update browser compatibility data for `RTCRtpEncodingParameters.maxFramerate`, which is now supported by both Firefox and Safari.

However I was told "it is a kitchen-sink of IDL definitions that the WebRTC working group deems as not sufficiently mature to be part of the main spec.". 
- Is that still the case? 
- - Is the intent to eventually move these into the main spec
- If so, what would be the specific plan for moving `RTCRtpEncodingParameters.maxFramerate`

**Comment by fippo** [comment]
maxFrameRate was moved out in https://github.com/w3c/webrtc-pc/issues/2357
@henbos given the recent discussion we had and that it is implemented in Chrome should this be revisited?

**Comment by aboba** [comment]
@hamishwillee Extensions that are not marked as "feature at risk" have been implemented in at least one browser, and are eligible to be moved into the WebRTC-PC specification. 

@dontcallmedom Do we have clarity on the process for moving implemented extensions into WebRTC-PC?

**Comment by dontcallmedom** [comment]
the process we've agreed to move features from -extensions to -pc is https://github.com/w3c/webrtc-charter/blob/gh-pages/merge-guide.md which reads
> to be considered for integration, a new extension must have:
> *   Reasonable test coverage
> *  Two passing implementation

From what I gather, this is actually now implemented in [Chromium](https://chromestatus.com/feature/6216116758118400), [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1611957) and Safari

The [WPT test results](https://wpt.fyi/results/webrtc-extensions/RTCRtpParameters-maxFramerate.html?label=master&label=experimental&aligned&q=%2Fwebrtc-extensions%2FRTCRtpParameters-maxFramerate.html) don't really reflect this show (all fail on firefox, 2 fail on Safari), although I'm not sure how concerning these failures are from an interop perspective.

More concerning is the report in https://bugzilla.mozilla.org/show_bug.cgi?id=1611957 that the spec'd behavior is incompatible with libwebrtc IIUC.

So it looks like after a bit of WPT work, this should be mostly ready to merge in the main spec

**Comment by aboba** [comment]
The [existing WPT test](https://github.com/web-platform-tests/wpt/blob/4092a1d93a/webrtc-extensions/RTCRtpParameters-maxFramerate.html) just determines that `maxFramerate` can be set and retrieved. 

The proposed FF test actually determines that `maxFramerate` affects the framerate.

**Comment by hamishwillee** [comment]
Thanks. I'll watch this then to track the property moving across specs.

> More concerning is the report in https://bugzilla.mozilla.org/show_bug.cgi?id=1611957 that the spec'd behavior is incompatible with libwebrtc IIUC.

FYI only. Apparently passing a 0 value for framerate crashes libwebrtc. The assignee of that bug says the intent is to get that fixed upstream and then modify Firefox  to match the spec. In the meantime FF just treats zero value as unconstrained.

**Comment by aboba** [comment]
PR to move `maxFramerate` to WebRTC-PC (now merged): https://github.com/w3c/webrtc-pc/pull/2785

**Comment by aboba** [comment]
Plan is to move implemented features from WebRTC-Extensions to WebRTC-PC.

**Comment by hamishwillee** [comment]
I've updated the spec in the browser compatibility data here: https://github.com/mdn/browser-compat-data/pull/18031. There are no other required MDN changes.

From my side this issue is addressed and can be closed. You might want to ping the MDN team or BCD team when other features are implemented, in case we miss these kinds of updates.

Thanks very much.

**Comment by aboba** [comment]
We will be reviewing the status of other WebRTC-Extensions features, and drop a line to the MDN team if there is a promotion.
