### ISSUE TITLE
Specify upper limit to playoutDelayHint

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-extensions#11]
Per discussions at #8, it would be good for specificity, interoperability and testability if we had an explicit upper limit to the hint. We don't want this API to be a way to buffer data for 10 minutes for example.

**Comment by henbos** [comment]
@kuddai [said](https://github.com/henbos/webrtc-extensions/issues/8#issuecomment-546965126) that current implementation in Chrome has "4 seconds for audio buffer and 10 seconds for video buffer"

How about we make the upper limit 4 seconds for both audio or video?

**Comment by kuddai** [comment]
Starting lower is the safer because if we ever want to increase the maximum then it won't break existing implementations that relying on that behavior.

What error type would be appropriate if user sets value beyond maximum allowed one?

@jan-ivar what do you think about 4 second as maximum value?

**Comment by henbos** [comment]
In webrtc-pc we use RangeError and InvalidModificationError. I guess if it's a hardcoded limit, RangeError makes sense, unless there are historical reasons for preferring one exception over another.
