### ISSUE TITLE
Integration of congestion control across SCTP and media

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-extensions#111]
From Harald (Issue 71): 

"A desire has been stated for integrating congestion control across SCTP and media, using a realtime congestion control protocol like Google Transport-wide-CC, SCREAM or NADA. There's some wishful thinking in -rtcweb-transport about how such a combo should work, but I think there are probably dragons once we try implementing it."

**Comment by alvestrand** [comment]
Discussed at TPAC 2022. Consensus seems that this is 1) hard to do and 2) not something that needs to show up at the Web API anyway (quality of implementation and/or IETF issue).

So closing in this repo.
