### ISSUE TITLE
header extension API: do we need enabled in setParameters?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-extensions#112]
it seems that the enabled property
  https://w3c.github.io/webrtc-extensions/#attributes-0
in setParameters is not implemented.

I think it is a headache to allow doing this for things like urn:3gpp:video-orientation which have implications for the whole pipeline.
Disabling an extension via (local) renegotiation solves the same problem, do we need this one?

**Comment by alvestrand** [comment]
On the principle of "let's not add complexity until we're sure we need it", I support removing this part from the spec.

**Comment by lgrahl** [comment]
Assuming it can be set via `setOfferedRtpHeaderExtensions` for negotiation, right? If so :+1: for getting rid of complexity. :slightly_smiling_face:

**Comment by fippo** [comment]
setOfferedRtpHeaderExtensions operates *before* offer (and I think answer but it seems we need another test for that), active in setParameters is dynamic "within the envelope of the negotiated sdp" (a term that I would prefer to avoid :-))
