### ISSUE TITLE
enable opus bite rate control by js api instead of SDP munging

### ISSUE THREAD

**Issue by bdrtc** [w3c/webrtc-extensions#117]
the default opus encode biterate is 30kb, and can only modify via sdp munging, acording to [Rfc 7587 ](https://www.rfc-editor.org/rfc/rfc7587#section-3.1.1), 

```
  o  8-12 kbit/s for NB speech,

   o  16-20 kbit/s for WB speech,

   o  28-40 kbit/s for FB speech,

   o  48-64 kbit/s for FB mono music, and

   o  64-128 kbit/s for FB stereo music.
```

30kbit/s is speech mode for mono , with the rapid growth of webrtc based RTC/live streaming system, some of them ,such as music streaming, they would like to set opus encode biterate to 48~64 kbit/s for mono music and 64-128 kbit/s for FB stereo music to achive high audio qulity.

we recommend enable opus bite rate setting by javascript api instead of SDP munging.

**Comment by fippo** [comment]
setParameters and maxbitrate works for this, no?
You don't need to do SDP munging (between createOffer and SLD) for the maxaveragebitrate setting since that is taken from the remote description.

**Comment by bdrtc** [comment]
> setParameters and maxbitrate works for this, no? You don't need to do SDP munging (between createOffer and SLD) for the maxaveragebitrate setting since that is taken from the remote description.

the maxaveragebitrate shoud control the encoder bite rate, the local/sender bite rate should init by offer but not remote answer, i think the current step need correct , for example, we can set video encode bite rate of sender , why can't for audio ?

**Comment by bdrtc** [comment]
> Shouldn't also the audio encoder take into account the audio track `contentHint` value to use `music` mode?

opus music encode mode is actived by configure encode bite rate to encoder, use bite rate interface should be more flexible ?

**Comment by fippo** [comment]
on [the sample page](https://webrtc.github.io/samples/src/content/peerconnection/audio/) paste this JS:
```
const sender = pc1.getSenders()[0];
p = sender.getParameters();
p.encodings[0].maxBitrate = 128000;
sender.setParameters(p);
```
if that doesn't work then there is a bug somewhere.

**Comment by bdrtc** [comment]
we test 

> on [the sample page](https://webrtc.github.io/samples/src/content/peerconnection/audio/) paste this JS:
> 
> ```
> const sender = pc1.getSenders()[0];
> p = sender.getParameters();
> p.encodings[0].maxBitrate = 128000;
> sender.setParameters(p);
> ```
> 
> if that doesn't work then there is a bug somewhere.
i made test, and it work, it seems no one use such parameter for audio in practice, anyway, this work as expect.
 Thanks for your time.
