### ISSUE TITLE
RTCRtpReceiver.playoutDelay...Hint or no Hint?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-extensions#123]
According WPT test status, all browsers have implemented playoutDelayHint:
https://wpt.fyi/results/webrtc-extensions/RTCRtpReceiver-playoutDelayHint.html?label=experimental&label=master&aligned

But the spec says [playoutDelay](https://w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelay) ever since [this PR](https://github.com/w3c/webrtc-extensions/pull/22/files)... ironically the referenced issue talks about not wanting to go back and forth on the name, but here we are.

Seems like we should update the spec to call it what the implementations do?

**Comment by henbos** [comment]
I think what happened was the person who originally worked on this left and we never updated the implementation to drop the "Hint". But seems kind of pointless to do so if everyone has implemented it with "Hint" in the name

**Comment by henbos** [comment]
Original issue where it was first renamed: https://github.com/w3c/webrtc-extensions/issues/20

**Comment by aboba** [comment]
@henbos Agree that it is pointless to rename it.

**Comment by henbos** [comment]
On second thought, [the test](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/webrtc-extensions/RTCRtpReceiver-playoutDelayHint.html) just sets values and doesn't really test any behavior.

Considering the tests checking initial values are not passing on Firefox/Safari, I'm guessing that playoutDelayHint is only implemented in Chromium-based browsers

**Comment by henbos** [comment]
For what it's worth the non-Chromium browsers have not implemented its alternative name either

**Comment by jan-ivar** [comment]
> I'm guessing that playoutDelayHint is only implemented in Chromium-based browsers

Correct. The WPT tests are pretty weak and misleading here. Tests should not pass in browsers that don't implement the feature. AFAIK they also don't test the spec correctly (throwing on > 4).

We're working to implement `playoutDelay` in [bug 1592988](https://bugzil.la/1592988), including improving tests to use the right name.

FWIW since Chrome's `playoutDelayHint` isn't following the spec which says to throw on values > 4, a name change might be safer web compat wise than making the existing API throw more. @henbos WYDT?

**Comment by henbos** [comment]
Is there any value in throwing on > 4? Being pragmatic, the best thing for web compat might be to use the name playoutDelayHint and to treat > 4 as 4?

**Comment by henbos** [comment]
If the differences with the specs are only these nit picks and the API is already in use
