### ISSUE TITLE
Potential web compat issue with setOfferedRtpHeaderExtensions

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-extensions#130]
I'm concerned about web compat over [this line](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-setofferedrtpheaderextensions):
- _"2. If ext.[uri](https://www.w3.org/TR/webrtc/#dom-rtcrtpheaderextensioncapability-uri) value is not present in [[[HeaderExtensionsToOffer]]](https://w3c.github.io/webrtc-extensions/#dfn-headerextensionstooffer), [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [NotSupportedError](https://webidl.spec.whatwg.org/#notsupportederror)."_

...where [[HeaderExtensionsToOffer]] is [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined). If _uri_ is a fixed string, that's a potential web compat headache.

How is JS expected to use this API in a web compatible manner?
 1. Come up with a subset tested to work in all browsers (today)?
 2. Detect UA and pick from a map?
 3. Write JS to pre-filter their input to [setOfferedRtpHeaderExtensions](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-setofferedrtpheaderextensions) using [headerExtensionsToOffer](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-headerextensionstooffer)?

I found no example showing predicted use of this API, but I could imagine some sites being lazy and setting a fixed array and not testing it in all browsers before going to production. This might cause calls to outright fail in a particular browser; or even work today but fail later once some browser makes a change.

This might also create a situation where browsers find it difficult to make changes later.

Throwing also seems redundant, since JS can already read [[HeaderExtensionsToOffer]] using [headerExtensionsToOffer](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-headerextensionstooffer), and can query [headerExtensionsNegotiated](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-headerextensionsnegotiated) for the net result.

Given this, maybe it's better for web compat to allow user agents to ignore values not present in [[HeaderExtensionsToOffer]]?

**Comment by alvestrand** [comment]
To figure out which header extensions are available:
Read the HeaderExtensionsToOffer attribute, it will contain all header extensions that are supported.

setOfferedHeaderExtensions does not remove anything from [[HeaderExtensionsToOffer]], it sets which of them are offered.

**Comment by alvestrand** [comment]
Closing as "not a problem".

**Comment by jan-ivar** [comment]
We should leave this issue open until all parties agree this is not a problem.

It remains unclear to me how JS is expected to use this API, let alone in a web compatible manner. There's no explainer or examples that I've found.

> To figure out which header extensions are available:
> Read the HeaderExtensionsToOffer attribute, it will contain all header extensions that are supported.

So is the intended use of this API something like this?
```js
setHeaders(headers) {
  headers = headers.filter(header => tc.headerExtensionsToOffer.some(({uri}) => uri == header.uri));
  tc.setOfferedRtpHeaderExtensions(headers);
}

setHeaders([{uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level", direction: "stopped"}]); // ?
```
Or is it intended to be something more setParameters-inspired, like this?
```js
const headers = structuredClone(tc.headerExtensionsToOffer); // defeat frozen array
for (const header of headers) {
  if (header.uri == "urn:ietf:params:rtp-hdrext:ssrc-audio-level") {
    header.direction = "stopped";
  }
}
tc.setOfferedRtpHeaderExtensions(headers);
```
The current algorirthm doesn't seem to require _extlist_.length  == [[HeaderExtensionsToOffer]].length, so it seems discrete inputs are supported, perhaps suggesting the former?

We went through similar design itereations for *setParameters*, until we landed on an approach that basically enforced the get/set pattern using a transactionId.

**Comment by fippo** [comment]
setParameters is the wrong mindset. setCodecPreferences is more similar.

We have a *major* problem of not being able to ship things that are not suitable to be enabled by default because they do not apply most of the time.
setOfferedRtpHeaderExtensions solves this by providing an API to say "oh you support this? I want it".

I do not think there is a web-compat issue here since SDP O/A (which is *not web*) will take care of this.

**Comment by jan-ivar** [comment]
> setParameters is the wrong mindset. setCodecPreferences is more similar.

Sure, let's use that. My point the same: set requires output from get as input, i.e. no hardcoded inputs, modulo https://github.com/w3c/webrtc-pc/issues/2805. For [example](https://jsfiddle.net/jib1/zu36q2d8/):
```js
const {codecs} = RTCRtpSender.getCapabilities("video");
codecs.sort((a, b) => b.mimeType.includes("H264") - a.mimeType.includes("H264"));
transceiver.setCodecPreferences(codecs);
```
Both setCodecPreferences and setParameters establish this get-before-set pattern, and setOfferedRtpHeaderExtensions violates it, because from what I can tell, this works:
```js
tc.setOfferedRtpHeaderExtensions([{uri: "urn:ietf:params:rtp-hdrext:ssrc-audio-level", direction: "stopped"}]);
```
This is what I think is bad and creates a web compat headache, because it's simpler to write code that breaks web compat that code that doesn't.

If you agree this wasn't the intent, which it sounds like you do if you're saying setCodecPreferences is the right model, then we can work to fix this. 

I've already identified a couple of problems that need fixing to make this work more like setCodecPreferences:
 1. structuredClone shouldn't be needed
 2. partial arrays are a sign input isn't from get, and shouldn't be allowed
 3. The algorithm doesn't weed out duplicates like setCodecPreferences does

**Comment by fippo** [comment]
setParameters is different because it is more dynamic and harder to come up with valid input.
It goes overboard even, why do you need to know what the other side negotiated if all you wanted to do is to set a maximum bitrate?

There is no hard set-before-get pattern for setCodecPreferences because the source and target are different objects - in one case the static RTCRtpSender.getCapabilities, in the other the peerconnection.
You can ask setCodecPreferences to only do VP8 or H264 CBP (which will implicitly work because those are MTI).

For setOfferedHeaderExtensions you could even use RTCRtpSender.getCapabilities('video').headerExtensions as input. However, that does not show header extensions that are not enabled by default, i.e. stopped.
Again, that is a valid model. We still need headerExtensionsToOffer because we can include non-default extensions there.

> partial arrays are a sign input isn't from get, and should be disallowed

This model does not work for codec preferences, they have no `direction` (as currently implemented; I would actually like it to have one but... backward compat). I  actually prefer using [].filter to the "set to stopped" method stipulated by setOfferedRtpHeaderExtensions. Both methods work however.

Please keep in mind that the pretense that RTCPeerConnection is used by "web developers" is a myth.

**Comment by jan-ivar** [comment]
I still think we should do the other 3 things I mentioned in https://github.com/w3c/webrtc-extensions/issues/130#issuecomment-1338493079 (avoid structuredClone, weed out duplicates and make it transactional).

**Comment by fippo** [comment]
Also note that while setCodecPreferences and setOfferedRtpHeaderExtensions do the same thing (modify what goes into SDP O/A) they work very different.
* setCodecPreferences is filtering with a set of discovered by the static getCapabilities(kind).codecs. We can not modify the semantics of that sadly but I hope [this proposal](https://github.com/w3c/webrtc-extensions/issues/100#issuecomment-1110005582) will address it some day in a way that retains backward compability. Note that passing [] resets to "the default".
* setOfferedRtpHeaderExtensions can take input either from static  getCapabilities(kind).headerExtensions or headerExtensionsToOffer. So this goes a bit more in the direction of the proposal a had already. Passing [] does *not* reset to the default but that is easy to do in JS, getCapabilities(kind).headerExtensions provides the default but this still seems worth changing.

**Comment by alvestrand** [comment]
The imagined usage when we designed this interface (a year ago) was

pc.setOfferedRtpHeaderExtensions([origin-timestamp: sendrecv, new-fancy-reporting: send])

with all the 14 other extensions being unchanged by the setOfferedRtpHeaderExtensions call, and an exception being thrown if new-fancy-reporting is either misspelled or unsupported.

What is now being suggested is that for this use case, we need to do:
```
extensions = pc.HeaderExtensionsToOffer();
extensions.find(uri=origin-timestamp).direction = sendrecv;
extensions.find(uri=new-fancy-reporting).direction = send;
pc.setOfferedRtpHeaderExtensions(extensions);
````
It's easy to shim one on top of the other, but I'm hesitant to declare that the new proposal is better than the old proposal without seeing a realistic use case that is simpler with the second semantics.

**Comment by jan-ivar** [comment]
The second case doesn't fail in some browsers and not others. That seems better.

The first case fails to explain why we have [headerExtensionsToOffer](https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-headerextensionstooffer).

It also seems unfair to compare sunny-case pseudo code that utterly fails to negotiate what the browser is capable of.

If we're going to compare simplicity, we should maybe compare realistic code with the same properties. Something like:
```js
try {
  transceiver.setOfferedRtpHeaderExtensions([
    {uri: "urn:ietf:params:rtp-hdrext:origin-timestamp", direction: "sendrecv"},
    {uri: "urn:ietf:params:rtp-hdrext:new-fancy-reporting", direction: "send"}
  ]);
} catch (e) {
  if (e.name != "NotSupportedError") throw e;
  transceiver.setOfferedRtpHeaderExtensions([
    {uri: "urn:ietf:params:rtp-hdrext:origin-timestamp", direction: "sendrecv"}
  ]);
}
```
vs.
```js
const headers = transceiver.getHeaderExtensionsToOffer(); // #137
for (const header of headers) {
  if (header.uri == "urn:ietf:params:rtp-hdrext:origin-timestamp") {
    header.direction = "sendrecv";
  }
  if (header.uri == "urn:ietf:params:rtp-hdrext:new-fancy-reporting") {
    header.direction = "send";
  }
}
transceiver.setOfferedRtpHeaderExtensions(headers);
```

**Comment by jan-ivar** [comment]
Disclaimer: they don't have exactly the same properties since the second doesn't fail over missing "origin-timestamp", but this seemed unclear from the use case since failure is rarely a realistic option IMHO, but I didn't want to belabor the point.

**Comment by fippo** [comment]
> but I'm hesitant to declare that the new proposal is better than the old proposal without seeing a realistic use case that is simpler

Your approach is simpler but it is inconsistent with the existing (and shipped) usage of setCodecPreferences which uses a reordered, potentially filtered list of codecs.
Hence the 🤯  between how each of us expected this to work. If only there had been an example in the disclaimer.

**Comment by fippo** [comment]
minutes: https://lists.w3.org/Archives/Public/public-webrtc/2023Jan/0056.html
We're going with get-modify-set, i.e. this approach from above:
```
const headers = transceiver.getHeaderExtensionsToOffer(); // #137
for (const header of headers) {
  if (header.uri == "urn:ietf:params:rtp-hdrext:origin-timestamp") {
    header.direction = "sendrecv";
  }
  if (header.uri == "urn:ietf:params:rtp-hdrext:new-fancy-reporting") {
    header.direction = "send";
  }
}
transceiver.setOfferedRtpHeaderExtensions(headers);
```
(naming might still change)

**Comment by henbos** [comment]
Completed as part of #142
