### ISSUE TITLE
Typo in section related to setOfferedRtpHeaderExtensions?

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-extensions#131]
"In the [set a session description](https://www.w3.org/TR/webrtc/#set-description) algorithm, add a step right after the step that sets transceiver.[[Sender]].[[SendCodecs]], saying "For each transciever, set [[[HeaderExtensionsNegotiated]]](https://w3c.github.io/webrtc-extensions/#dfn-headerextensionsnegotiated) to an empty list, and then for each "**_a=hdrext_**" line, add an appropriate [RTCRtpHeaderExtensionCapability](https://www.w3.org/TR/webrtc/#dom-rtcrtpheaderextensioncapability) to the list."

There is no such thing as an a=hdrext SDP attribute, I'm guessing this was supposed to be a=extmap?

**Comment by alvestrand** [comment]
Yes, that's a typo. Thanks for catching it!
