### ISSUE TITLE
headerExtensionsToOffer entries are mutable which is surprising

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-extensions#136]
The following behavior seems unintentional and surprising:
```js
if (transceiver.headerExtensionsToOffer[0].direction == "sendrecv") {
  transceiver.headerExtensionsToOffer[0].direction = "stopped";
  console.log(transceiver.headerExtensionsToOffer[0].direction); // "stopped"
}
```
This behavior is from the [spec](https://w3c.github.io/webrtc-extensions/#rtcrtptransceiver-interface) using FrozenArray on a dictionary:
```webidl
readonly attribute FrozenArray<RTCRtpHeaderExtensionCapability> headerExtensionsToOffer;
```
Since [array freezing](https://webidl.spec.whatwg.org/#es-frozen-array) is shallow (uses _"[SetIntegrityLevel](https://tc39.es/ecma262/#sec-setintegritylevel)(array, "frozen")"_, same as [Object.freeze](https://tc39.es/ecma262/#sec-object.freeze) —see [fiddle](https://jsfiddle.net/jib1/5dt36qao/)) it only ensures entries cannot be swapped out, but the entries themselves (in this case pojo caches of the dictionary) remain mutable. These mutations are not observable to the user agent, but _are_ observable to JS, which seems confusing. https://github.com/whatwg/webidl/issues/348

**Comment by henbos** [comment]
Completed as part of https://github.com/w3c/webrtc-extensions/pull/142
