### ISSUE TITLE
Not clear what should happen if header extensions are inconsistent across bundled transports

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-extensions#140]
Quoting @alvestrand out of context from https://github.com/w3c/webrtc-extensions/issues/132#issuecomment-1336412605:

> (It's a side effect of the Unified Plan decision that headers are negotiated per media session, but the result has to be consistent across all media sections bundled to a single transport.)

That made me wonder, what if I use BUNDLE and on transceiverA I set header extension X but not Y and on transceiverB I set header extension Y but not X.

If I'm reading the spec right, it doesn't look like we're ensuring consistency here. Does that mean the SDP offer may be rejected?

**Comment by henbos** [comment]
Considering non-BUNDLE is mostly for backwards-compat, is there any reason why we would even want to support different header extensions on different m= sections? Maybe the API should be per-kind (audio or video) but be copy-pasted to all m= sections of the same kind, regardless if BUNDLE or non-BUNDLE is used. Why make it complicated for a use case that's not interesting?

Just a thought... thinking aloud

**Comment by henbos** [comment]
Alternatively should doing "get-modify-set" (new pattern as of #130) modify all transceivers if BUNDLE is used or should the user of the API have to modify all transceivers manually?

And if a new transciever is added, should it default to what the other transceivers are doing, or should you need to configure it yourself?

We probably don't want onnegotiationneeded to be able to fire when in an inconsistent state, but so far all the header extension APIs are synchronous

**Comment by fippo** [comment]
Even with BUNDLE you can have transceiverA use header extensions 1,2,3 but transceiverB use only 2,3 (common example of this is bundled audio and video)
I don't think the header extension API changes this.

**Comment by henbos** [comment]
Oh? If this is a non-issue I would be very happy to just close this

**Comment by fippo** [comment]
It is an issue. Lets take this (only works in chrome canary with experimental web platform flags and uses the old semantics)
https://jsfiddle.net/fippo/o2rbhp4v/1/

It shows that the first transceiver still has all header extensions even though the video-timing one was removed.
It will not show up in the offer when it is removed from all transceivers.

Likewise, enabling a non-default extension for one transceiver shows them in all transceivers.
Last but not least disabling something supported by two transceivers of different kinds on one kind still shows up on the other: https://jsfiddle.net/fippo/o2rbhp4v/2/

I'd say we have an implementation bug here and it should not show extensions stopped for a particular transceiver.

**Comment by fippo** [comment]
I think this is a bug in Chrome.
https://www.rfc-editor.org/rfc/rfc9143.html#name-rtp-header-extensions-consi
only mandates same ids but not same header extensions.

**Comment by fippo** [comment]
https://jsfiddle.net/fippo/o2rbhp4v/1/ behaves as expected in Chrome 112.0.5574.0
This was previously caused by the `where direction is not "stopped"` bit of https://w3c.github.io/webrtc-extensions/#modifications-to-existing-procedures-0
Will add those as tests

**Comment by henbos** [comment]
Thanks fippo! But sounds like the consistency is not about which ones are used, only their ids, and that this being per-transceiver still makes sense, so I'll close this spec issue
