### ISSUE TITLE
Header extension: direction woes and renames

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-extensions#141]
The direction could refer to any of the following:
- What we want to negotiate.
- What we have already negotiated.
- What the user agent uses by default.
- What the user agent is capable of doing.

For example, a header extension might be "stopped" by default, we want to negotiate it as "sendonly" but we are capable of negotiating it as "sendrecv" and at the moment nothing is negotiated, so "stopped".

What's even more confusion about direction is that currently, header extension capabilities are spread out across both `RTCRtpSender.getCapabilities(kind).headerExtensions` and `RTCRtpReciever.getCapabilities(kind).headerExtensions`.

Here's my proposal to reduce confusion and get a more unified API shape, plus some renames while we're at it.
This potentially fixes #130, #132, #137 and #136.

```
partial interface RTCRtpTransciever {
  // Replaces RTCRtpSender/Receiver.getCapabilities(kind).headerExtensions.
  // exts[i].direction refers to what is default, e.g. this could be "stopped" even
  // though it is possible to negotiate it.
  static sequence<RTCRtpHeaderExtensionCapability> getDefaultHeaderExtensions(DOMString kind);

  // Rename of headerExtensionsToOffer, fixes #132.
  // Not using FrozenArray, fixes #137 and #136.
  sequence<RTCRtpHeaderExtensionCapability> getHeaderExtensionsToNegotiate();

  // This gives us the get-modify-set pattern, fixing #130.
  void setHeaderExtensionsToNegotiate(sequence<RTCRtpHeaderExtensionCapability> exts);

  // What has been negotiated already.
  sequence<RTCRtpHeaderExtensionCapability> getNegotiatedHeaderExtensions();
};
```

Here's an example usage:
```
const extensions = transciever.getHeaderExtensionsToNegotiate();
const desiredExtension = extensions.find(ext => ext.uri == 'foo');
if (desiredExtension) {
  // The app should know what directions are applicable to a particular header extension,
  // but if 'sendrecv' isn't applicable, the UA will downgrade this to 'sendonly' or
  // 'recvonly' as necessary. getHeaderExtensionsToNegotiate() will let you know.
  desiredExtension.direction = 'sendrecv';
}
transceiver.setHeaderExtensionsToNegotiate(extensions);

// After an O/A, transceiver.getNegotiatedHeaderExtensions() will match `extensions`
// if the other endpoints accepted everything, otherwise directions may be less.
```

**Comment by fippo** [comment]
I do not think we need `getDefaultHeaderExtensions`.
`getHeaderExtensionsToNegotiate` will always list the extensions the UA supports one way or another.

The direction describes the desired negotiation status.  This means that once we go from sendrecv to stopped we no longer know that we can go back to sendrecv. But we don't need that, why would the UA include an extension that can't be set to sendrecv in the set?
(csrc-audio-level might be a counterexample, it does not make sense for the browser to send but if as dev you modify it first to stopped and then 'on' again why do you expect this to work even? We can still reject an invalid modification attempt))

**Comment by henbos** [comment]
> I do not think we need getDefaultHeaderExtensions.
> getHeaderExtensionsToNegotiate will always list the extensions the UA supports one way or another.

I see your point - if you do `addTransceiver()` and then `getHeaderExtensionToNegotiate()` you get the defaults already. This might not be the case if the transceiver was created by a remote SDP offer, in which case it would be initialized to whatever is currently on offer (minus anything that the user agent doesn't support), but you might not care to examine the user agent's defaults in this case either? I'd be fine with removing `getDefaultHeaderExtensions()` from this proposal.

**Comment by henbos** [comment]
@jan-ivar who filed a lot of the other issues, what are your thoughts on this proposal?

**Comment by fippo** [comment]
We might also call this `getHeaderExtensions()` and have, transceiver-like, currentDirection set to null before negotiation which avoids `getNegotiatedHeaderExtensions`.

But that does not solve the problem of discovery and header extensions are different from transceivers because you don't have to explicitly add them to an empty set.
