### ISSUE TITLE
Header extension API lets the remote end control the remote preferences

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-extensions#153]
https://w3c.github.io/webrtc-extensions/#rtp-header-extension-control-modifications
> If description is of type "[offer](https://www.w3.org/TR/webrtc/#dom-rtcsdptype-offer)", then for each extension in transceiver.[[[HeaderExtensionsToNegotiate]]](https://w3c.github.io/webrtc-extensions/#dfn-headerextensionstonegotiate), run the following steps:
> [...]
>>Set extension.[direction](https://w3c.github.io/webrtc-extensions/#dom-rtcrtpheaderextensioncapability-direction) to offeredDirection.

This lets the remote end control what the local end offers. This is not what the API intends to do (primarily enabling non-default header extensions) nor is it consistent with the SDP principles involved which (in some interpretations) enable sending an extension when the remote offers it already.

Suggested fix: remove those steps.

**Comment by henbos** [comment]
Agree this part was a mistake, we should just delete it. Both endpoints controlling what is in their part of the SDP is sufficient. It signals their preference and since the remote endpoint is allowed to both add and remove in the answer there is no need to make offers and answers match either
