### ISSUE TITLE
Does playoutDelay of video affect jitter buffer of synced audio and vice versa?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-extensions#157]
The spec has [this non-normative note](https://w3c.github.io/webrtc-extensions/#dfn-maximum-allowed-delay):
 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3136226/230648649-08b6e7f3-a87f-41e8-8d9b-b59210197fc9.png">

What does _"the largest of those hints will take precedence in synchronization mechanism"_ mean? Does it mean:
1. tracks get synced at playout without the benefit of deeper jitter buffers?
2. tracks get the same (larger) jitter buffer depth?

As mentioned in #156, jitter buffer depth is JS-observable through receiver.getStats(), so we should be clear.

Notes are [non-normative](https://w3c.github.io/webrtc-extensions/#conformance) in this spec, and I find no normative steps to support 2, which suggests 1.

Was 1 the intent? Is 2 useful? If so, do we wish to specify it? Any downsides to doing so? Either way we should clarify.

**Comment by bdrtc** [comment]
Yes ,from our test, playoutDelay of video will be affected by av sync, i have metioned this before in [nv-use-case](https://github.com/w3c/webrtc-nv-use-cases/issues/78), user should disable A/V sync when use playoutDelay to achive low delay of video.
