### ISSUE TITLE
Maintain an internal slot of candidate pairs that are valid inputs to RTCIceTransport operations

### ISSUE THREAD

**Issue by sam-vi** [w3c/webrtc-extensions#188]
An internal slot of [[ActiveCandidatePairs]] can track candidate pairs that are
- added when sent in onicecandidatepairadd
- removed when sent in onicecandidatepairremove, which is not canceled
- removed when supplied to removeCandidatePairs

This makes it explicit and possible to validate synchronously whether an input to an RTCIceTransport operation is valid.

**Comment by jan-ivar** [comment]
It might make sense to build this on top of https://github.com/w3c/webrtc-pc/issues/2906.
