### ISSUE TITLE
Normative reference to googlesource.com

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-extensions#216]
[This](https://w3c.github.io/webrtc-extensions/#bib-rtp-ext-capture-time) normatively references a non-standards-track document:
> [RTP-EXT-CAPTURE-TIME]
    [RTP Header Extension for Absolute Capture Time](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-capture-time). WebRTC Project. Experimental RTP Header Extension. URL: https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-capture-time

This doesn't comply with [W3C policy](https://www.w3.org/Guide/process/tilt/normative-references), which says it blocks _"transitions on the [W3C Recommendation track](https://www.w3.org/Consortium/Process/#Reports)"_.

The target document says: _"**Status:** This extension is defined here to allow for experimentation. Once experience has shown that it is useful, we intend to make a proposal based on it for standardization in the IETF. Contact [chxg@google.com](mailto:chxg@google.com) for more info."_

Last touched in [Feb 2020](https://webrtc.googlesource.com/src/+/73ff1ffd0f29185d366164d3ede341b51730afcd). Looks like this needs to be standardized in the IETF and registered [here](https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-10)? If someone could reach out to the author or another person willing to drive this to standardization that would be great!

**Comment by dontcallmedom** [comment]
see also #201

**Comment by jan-ivar** [comment]
Closing as a dup of #201.
