### ISSUE TITLE
ReSpec errors from duplicate definitions of RTCIceCandidatePair

### ISSUE THREAD

**Issue by sam-vi** [w3c/webrtc-extensions#217]
Ref: https://github.com/w3c/webrtc-pc/issues/2930.

With the conversion of `RTCIceCandidatePair` from a dictionary to an interface, the XRef database contains some ambiguous duplicate definitions with differing types from multiple version of the "webrtc" spec with the same spec ID:
- `RTCIceCandidatePair`: https://respec.org/xref/?term=RTCIceCandidatePair&specs=webrtc&types=_IDL_
- `RTCIceCandidatePair.local`: https://respec.org/xref/?term=local&specs=webrtc&types=attribute%2Cconst%2Cdict-member&for=RTCIceCandidatePair
- `RTCIceCandidatePair.remote`: https://respec.org/xref/?term=remote&specs=webrtc&types=attribute%2Cdict-member%2Cconst&for=RTCIceCandidatePair

This leads to validation errors in [webrtc-extensions](https://w3c.github.io/webrtc-extensions/#respec-offender-definition-is-ambiguous) when linking to these definitions.

Possibly related bug: speced/respec#4307.

**Comment by dontcallmedom** [comment]
the "right" way to fix this will involve re-publishing the current editors draft of the WebRTC spec on /TR, which mostly needs approval from the WG

**Comment by dontcallmedom** [comment]
With the republication of the WebRTC spec on TR, that problem is now resolved
