### ISSUE TITLE
Mixed-codec simulcast proposal

### ISSUE THREAD

**Issue by Orphis** [w3c/webrtc-extensions#43]
It would be interesting to give users more control over which codec is used for each simulcast layer.
We used to have `codecPayloadType` that took at payload type (codec id negotiated after O/A) but it was removed as it wasn't well designed (PT not known before O/A) and no implementations supported it.

We have a few use cases in mind where mixed codecs could be used, for example using a lower layer with a higher complexity codec (for example software AV1) to get more efficiency and a higher level with another relatively simpler codec (VP8/9).

I imagine that the each simulcast layer could have an array of codecs, listed in the same way as with `setCodecPreferences()`.

Goals are: 

- Filter out unwanted codecs for specific layers
- Override the priority of the codecs negotiated during the O/A.
- Per-layer control of features like FEC or RTX.
- **CAN'T** add new codecs with this API, we are limited to what is in the O/A.

Let me know if you want a more detailed API proposal with IDL.

**Comment by murillo128** [comment]
what would be the benefit of doing this on a simulcast sender vs using several senders?

**Comment by aboba** [comment]
@orphis - would you like some time on the agenda of the July 8 meeting to discuss this proposal?

**Comment by Orphis** [comment]
Bandwidth allocation would work better if layers are logically grouped in a single sender. The grouping would probably also need to be signaled OOB which is undesirable.

**Comment by Orphis** [comment]
@aboba Maybe! I would like to receive a bit more feedback here first before taking time on our usually busy meetings.

**Comment by murillo128** [comment]
@Orphis given that bandwidth is estimated per transport, how is it easier to split bandwidth between encodings (which are independent as per your original use case) than between streams in same transport?

Don't get me wrong, I am all in for adding more apis for controlling the underlaying behaviour, but in this case, I think that we should be able to do the same thing either with this mixed-codec simulcast proposal than with using several senders. But specifically the bandwidth allocation of the estimated bitrate between the different streams/layers is under specified in webrtc, and relaying on the internal browser implementation doesn't seem a good way to go.

**Comment by Orphis** [comment]
It might underspecified, but if resources are limited (for example bandwidth or compute), we said (in some other issue) that higher priority would be given to the first layers in the `encodings` array.
We don't have any way to prioritize bandwidth allocation between different senders in the same peer connection, so we'd lose an essential feature.

**Comment by murillo128** [comment]
Could you point me to that issue, please?

Shouldn't it be easier to solve the issue of allocating bandwidth to different senders in webrtc spec? After all, the use case of sending camera and screenshare and being able to split/allocate the bitrate/cpu between them is very common.

**Comment by aboba** [comment]
I have added an item on the agenda of the July 8 WEBRTC WG Virtual Interim to discuss this if it would be useful.  Slides are here: 
https://docs.google.com/presentation/d/1rHXd5vxv_ME5r2TgpLPhJlD2iq0lcxQCsYbuT6fg0dc/

**Comment by Orphis** [comment]
@murillo128 Couldn't find the issue I thought we talked about it, but I found this in webrtc-pc:

> [SDP-SIMULCAST] section 5.2 specifies that the order of RIDs in the a=simulcast line suggests a proposed order of preference. If the browser decides not to transmit all encodings, one should expect it to stop sending the last encoding in the list first.

I think we might have talked about it in some of the monthly meetings.

**Comment by aboba** [comment]
Slide is here: https://docs.google.com/presentation/d/1rHXd5vxv_ME5r2TgpLPhJlD2iq0lcxQCsYbuT6fg0dc/edit?userstoinvite=varun%40callstats.io&ts=5ef67a8e&actionButton=1#slide=id.g8216c65274_46_116

**Comment by Orphis** [comment]
Thanks! Added a few more slides about it.

**Comment by aboba** [comment]
With AV1 now supported in WebRTC, support for mixed-codec simulcast has a real use case.

**Comment by aboba** [comment]
@orphis Any cycles available for a PR?

**Comment by aboba** [comment]
Is this worth discussing at TPAC 2022?

**Comment by Orphis** [comment]
Only if we find someone committing to implement it, so I don't think we should at the moment. We can revisit this later.

**Comment by henbos** [comment]
I have a similar but more detailed proposal over at https://github.com/w3c/webrtc-extensions/issues/126, I propose we continue the discussion over there
