### ISSUE TITLE
RTCRtpSender.getCapabilities() may not return correct information in sync

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-extensions#49]
Chrome has found a [case](https://bugs.chromium.org/p/chromium/issues/detail?id=1047994) where getCapabilities() is going to have issues with delivering correct capability information about codec availability synchronously.

The two immediately obvious workarounds are:

- Fail the call with a LATER error code (but since it's a static method, there's no place to fire a "later has arrived" event at)
- Change the signature to async

The latter would be preferable from an architectural viewpoint, but has some compatibility issues.

**Comment by alvestrand** [comment]
We seem to have another case where the sync nature of the interface causes some interesting issues: Slow initialization (?) of USB cameras. We know that the camera is there long before we know what the capabilities of the device is.

https://crbug.com/1153290

**Comment by henbos** [comment]
See also https://github.com/w3c/webrtc-pc/pull/2597

**Comment by henbos** [comment]
Or more importantly, slides https://docs.google.com/presentation/d/17Z_vR4pOXn-9wthiqbM9GC7JE7vfbdNffEedBPqj1Mw/edit#slide=id.gad716a442e_1_0

**Comment by henbos** [comment]
The result of the previous interim was to add this note:
https://github.com/w3c/webrtc-pc/pull/2617/files

It says that the capabilities in getCapabilities() and in the SDP from createOffer()/createAnswer() need to be consistent.

I think to really pinpoint when capabilities are discovered and exposed would require normative steps and is thus webrtc-extensions territory, but I don't think this needs to be tackled in the January interim. This may be come a non issue with media capabilities or if we add an async API.

**Comment by aboba** [comment]
@alvestrand Is there interest in implementing an async version of `getCapabilities()` if we were to specify one?

**Comment by aboba** [comment]
@alvestrand It seems like the current direction is to add functionality to Media Capabilities rather than updating `RTCRtpSender.getCapabilities()`. If so, should we close this issue?

**Comment by youennf** [comment]
Makes sense to close it as we want to progressively remove this support (see https://github.com/w3c/webrtc-extensions/issues/95)

**Comment by alvestrand** [comment]
I agree. Let's focus on #95 for any new functionality, and keep getCapabilities as-is in the spec for backwards compatibility.
