### ISSUE TITLE
Consider an API for non-delivered messages in SCTP datachannels

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-extensions#50]
Since I entered a discussion where someone was hoping that datachannels would tell them when they were unable to deliver a message (at the moment they don't):

Perhaps we should consider:

a) whether SCTP_SEND_FAILED_EVENT from https://tools.ietf.org/html/rfc6458#section-6.1.11 reliably indicates "this message has been discarded from the send queue and delivery (or non-delivery) can't be guaranteed" (in spec, and/or in current implementations)

b) whether that indication should be reflected as some kind of event on the datachannel API.

Only makes sense for unreliable datachannels, I think.
This is definitely an extension, not something for WebRTC-1.0.

**Comment by alvestrand** [comment]
asking @orphis on the question of SCTP_SEND_FAILED_EVENT.

It seems likely that we'll just close this, it's complicated, and the specific use case doesn't seem compelling.

**Comment by lgrahl** [comment]
I'm unsure whether abandoning a message even triggers `SCTP_SEND_FAILED_EVENT` on the sender side. Would have to dig in the spec what's the case here, but maybe @tuexen knows it without looking. Even if it does, I don't see value in it unless all unsent messages can be reliably recovered from it **immediately** when ICE goes into failed. That would make it somewhat interesting (especially for reliable channels).
Note that there's also `SCTP_PARTIAL_DELIVERY_EVENT` which indicates that some parts of a message have been received but it's being abandoned.

But I'm not convinced this is worth the effort. If an application really wants to make sure it doesn't lose messages (reliable) or needs to know which messages have been abandoned (unreliable), it's fairly easy and safer (talk browser bugs here) to count and ack by itself.

**Comment by Orphis** [comment]
On a technical level, it should be straightforward in case of `SCTP_SEND_FAILED_EVENT` to return the failed message in the onerror event of a data channel. We could already expose the SCTP error in the `sctpCauseCode` dictionary member of `RTCError` as well.

In case of a `SCTP_PARTIAL_DELIVERY_EVENT`, wouldn't you also receive `SCTP_SEND_FAILED_EVENT` too?

**Comment by lgrahl** [comment]
> On a technical level, it should be straightforward in case of `SCTP_SEND_FAILED_EVENT` to return the failed message in the onerror event of a data channel.

It doesn't really fit the definition of the error event though. Also, it only triggers on the receiver side and messages that have never been sent will not even trigger this, so it's completely arbitrary and doesn't tell you much. You do need the event though to clear the receive buffers when running in message interleave mode.

> In case of a `SCTP_PARTIAL_DELIVERY_EVENT`, wouldn't you also receive `SCTP_SEND_FAILED_EVENT` too?

Like I said, I'm not sure if abandoning a message that was marked as "allowed to be unreliable" even triggers this event. If it does, then probably yes.

**Comment by alvestrand** [comment]
tagging @boivie - I get the message that "it's complicated", which is an excellent reason for not adding it to the API.

**Comment by boivie** [comment]
It's an interesting idea. I have been considering the same for the purpose of monitoring some signaling messages that are sent unordered with partial reliability, where it's hard to create a good higher level protocol.

With the current events from rfc6458, I think it would be hard to make something easily. With a custom implementation, it wouldn't be hard to the SCTP implementation to provide message lifecycle events, if requested. A message that is sent on a socket would have a state diagram with states:
 * Queued (in send buffer, not yet assigned a MID to, and no fragment put on the wire)
 * Partially sent (for multi-fragment messages where at least one fragment has been put on the write)
 * Fully sent (all fragments have been put on the wire, but not yet acknowledged)
 * Acked (received has sent a SACK including it. Here, if we assume all SACKs are non-renegable, this is straightforward)
 * Lost (Message expired with not all fragments ever put on the wire)
 * Probably lost (Message expired before acked, but with all fragments sent at least once, so received _may_ have received it)

All states are not applicable for all messages, and all states may not be interesting to inform the upper layer about, but it is possible.

In `dcsct::SendOptions`, I thought about adding a new parameter, e.g. `uint64_t client_message_id`, which if non-zero, would trigger callbacks whenever the message changes states, and using `client_message_id` to identify the message.

I might prototype it, and see if there are pitfalls. Partial reliability is one, of course, but also stream resetting (which may throw away messages) and if an association detects that the peer has restarted (receives an INIT, and restarts the association), as that may trigger resending of messages and reset their states.

If you are only interested in knowledge if a message was successfully received, I do agree that doing that in a higher layer protocol would be the reasonable choice. The other states may be harder or even impossible to find out without information from the SCTP socket implementation.

**Comment by alvestrand** [comment]
The bogeyman of "message-was-lost" notifications is of course the message that was successfully delivered, but the information that it was delivered was lost and not delivered until the connection broke down for other reasons - so that would result in an "I don't know whether this was delivered or not" notification. Pitfalls galore!

**Comment by lgrahl** [comment]
I'd say the question is whether the importance of the use cases outweighs the potential pitfalls (and I think there will be more once we examine this as part of the WebRTC state machine) and complexity. :slightly_smiling_face:

**Comment by tuexen** [comment]
> I'm unsure whether abandoning a message even triggers `SCTP_SEND_FAILED_EVENT` on the sender side. Would have to dig in the spec what's the case here, but maybe @tuexen knows it without looking. Even if it does, I don't see value in it unless all unsent messages can be reliably recovered from it **immediately** when ICE goes into failed. That would make it somewhat interesting (especially for reliable channels).

[RFC 6458](https://datatracker.ietf.org/doc/html/rfc6458#section-6.1.11) says:
```
If SCTP cannot deliver a message, it can return back the message as a
notification if the SCTP_SEND_FAILED_EVENT event is enabled.
```

I consider abandoning a user message as not delivering it. So, yes, the FreeBSD stack and therefore usrsctp triggers this notification in case of PR-SCTP abandoning a user message.

**Comment by tuexen** [comment]
> It's an interesting idea. I have been considering the same for the purpose of monitoring some signaling messages that are sent unordered with partial reliability, where it's hard to create a good higher level protocol.

Just to give some background, why `SCTP_SEND_FAILED_EVENT` does exist. SCTP was originally designed for transporting signalling messages and they must be delivered in sequence and it is better to drop messages than to deliver them in the wrong sequence. To keep the number of lost user messages as small as possible, the SCTP stack had to give the user messages back to the application in case the SCTP association fails. Then the application would send these messages on a different association (most likely to a different peer in a cluster), but only the messages which have no been sent at all, since only for them the sequence of deliver can be guaranteed to be correct.

This adds complexity to the API and the implementation of the upper layer, so I would only recommend using it if the application requires it or at least has a benefit.

> 
> With the current events from rfc6458, I think it would be hard to make something easily. With a custom implementation, it wouldn't be hard to the SCTP implementation to provide message lifecycle events, if requested. A message that is sent on a socket would have a state diagram with states:
> 
> * Queued (in send buffer, not yet assigned a MID to, and no fragment put on the wire)
> * Partially sent (for multi-fragment messages where at least one fragment has been put on the write)
> * Fully sent (all fragments have been put on the wire, but not yet acknowledged)
> * Acked (received has sent a SACK including it. Here, if we assume all SACKs are non-renegable, this is straightforward)
> * Lost (Message expired with not all fragments ever put on the wire)
> * Probably lost (Message expired before acked, but with all fragments sent at least once, so received _may_ have received it)

You could add some more values to the `ssfe_flags` of `struct sctp_send_failed_event`. But I would suggest to keep things as simple as possible. So only add values your  application really needs.

> 
> All states are not applicable for all messages, and all states may not be interesting to inform the upper layer about, but it is possible.
> 
> In `dcsctp::SendOptions`, I thought about adding a new parameter, e.g. `uint64_t client_message_id`, which if non-zero, would trigger callbacks whenever the message changes states, and using `client_message_id` to identify the message.

Doesn't `snd_context` of the `struct sctp_sndinfo` gives you what you want?

> 
> I might prototype it, and see if there are pitfalls. Partial reliability is one, of course, but also stream resetting (which may throw away messages) and if an association detects that the peer has restarted (receives an INIT, and restarts the association), as that may trigger resending of messages and reset their states.

Why is stream resetting (as used by WebRTC) throwing away messages? Closing a data channel is a reliable operation.

Why does restarting of an association result in resending of messages? When an association restarts, all buffered messages are given back to the application. SCTP does not resend anything.

> 
> If you are only interested in knowledge if a message was successfully received, I do agree that doing that in a higher layer protocol would be the reasonable choice. The other states may be harder or even impossible to find out without information from the SCTP socket implementation.

**Comment by tuexen** [comment]
> I'd say the question is whether the importance of the use cases outweighs the potential pitfalls (and I think there will be more once we examine this as part of the WebRTC state machine) and complexity. 🙂

I second what @alvestrand and @lgrahl said: keep the API as simple as possible for the required use case. I have seen a lot of cases in which the SCTP socket API, which is specified in an RFC, was used incorrectly and therefore the application behave sometimes in a strange way. Some developers start to work around the strange behaviours since they do not realise that the application has a bug the y need to fix.

@boivie : Can you precisely describe the need the application has and which you currently can not implement using the data channel API? I think this is the API currently exposed, not the SCTP API. One just needs to figure out how to provide the data channel API by using the SCTP API. At least in my view...

**Comment by aboba** [comment]
What is the use case for this API?  Is the goal to provide statistics so as to enable monitoring of application performance?  Or is there something that we are enabling the application to do? 

I do not believe that SCTP-layer delivery information is directly actionable within a browser applications. A sending application cannot assume that the receiving application has gotten a message without an application-layer acknowledgement;  reception at the SCTP layer does not imply successful application processing.  Similarly, an application cannot use delivery information to implement its own congestion control or flow control (e.g. attempting to do so will conflict with SCTP's own mechanisms).

**Comment by youennf** [comment]
Let's close the issue until we can clarify precisely the usecase for such API.
