### ISSUE TITLE
Add normative steps to getCapabilities() or deprecate it in favor of an async API 

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-extensions#57]
It seems several interpretations for how to implement getCapabilities() is possible:

1. Query capabilities on createOffer() and expose them in subsequent getCapabilities() calls.
2. Like 1) but also do this at setRemoteDescription(offer).
3. Have getCapabilities() block so that it can return even HW capabilities.
4. ???

We need to add normative steps or deprecate it in favor of an async API.

**Comment by aboba** [comment]
My question about #1 is what happens when setCodecPreferences is used to disable a codec, and createAnswer() is called. Does the disabled codec then disappear from getCapabilities()?  

Having getCapabilities() block does not seem worth considering.

**Comment by henbos** [comment]
getCapabilities() is an "optimistic view of the capabilities". Because it is a static method it cannot do things on a per-peer connection basis. So it doesn't matter if the remote end only offered you VP8 or if you locally said you only care about VP9, you would still see that you are capable of doing VP8, VP9 and H264 if 1) you can do this, and 2) the implementation knows this.

It's just what you could do, not what is on offer. So the question of interest is: what do you know, and when?

In fact, a HW agnostic implementation could be over-optimistic and report HW-only codecs on a device that doesn't do HW. "If I don't know this _isn't_ supported, I could say that it _is_ (even if it turns out that I'm wrong!)" is, as far as I can tell, a valid interpretation from the words of the specs, but we did not intend that.

In the end this only affects the "codec preferences" that is "input" to the "JSEP algorithms" so anything that doesn't break JSEP would probably be okay-ish to do, but depending on what we do would have great consequences on the usefulness of the API.

**Comment by youennf** [comment]
AIUI, we want to ensure that calling setCodecPreferences synchronously after getCapabilities should not throw.
Similarly, if getCapabilites moves to async, the idea would be that calling setCodecPreferences in the promise resolution microtask would not throw. There should be a similar guarantee if codec capabilities are queried through Media Capabilities.

Option 1 and 2 do not solve the usual flow of:
1. creating a peer connection.
2. adding a transceiver
3. calling getCapabilities
3. setting the codec accordingly
4. calling createOffer

Option 3 is really an implementation choice.

My inclination would be to try something like:
1. Deprecate codecs in synchronous getCapabilities. In the meantime, make it clear to developers of its shortcomings
2. Validate a synchronous getCapabilities is good enough for non codec information
3. Validate/Make sure media capabilities as input to setCodecPreferences is a superior replacement

I would go with an async getCapabilities if we cannot validate 2. or 3.

**Comment by henbos** [comment]
> Option 3 is really an implementation choice.

I know this one (blocking-invoke) is "taboo", but in terms owning our mistakes, this seems to be the only option that does not break the usual flow that you mentioned. So it's not "just an implementation choice" if we decide to take that path, but I understand if we don't want to go there.

> Validate/Make sure media capabilities as input to setCodecPreferences is a superior replacement

I like this option. But I agree that if we cannot do that then we do need an async replacement.

**Comment by henbos** [comment]
In any case, if we decide to deprecate it because it isn't good enough, we should at least agree on what aspects of it isn't good enough by deciding which interpretation is the right interpretation.

**Comment by youennf** [comment]
> 3\. Validate/Make sure media capabilities as input to setCodecPreferences is a superior replacement

Media capabilities works fine if using setCodecPreferences to use exactly one codec.
I am not sure it works well if the page wants to give a restricted ordered list of codecs.

**Comment by youennf** [comment]
> So it's not "just an implementation choice" if we decide to take that path, but I understand if we don't want to go there.

It is an implementation choice in the sense that getCapabilities is an optimistic view.
How close it is from the actual real view is implementation dependent.

**Comment by henbos** [comment]
Right, you could always over-report...

**Comment by aboba** [comment]
At this point, I don't seem much implementer interest in replacing `getCapabilities()` with an async API.  To some extent the existing specification does document implementation-dependent behavior (e.g. that `getCapabilities()` can return different information when called before versus after `createOffer()` or `createAnswer()`.  So can we close this issue?

**Comment by alvestrand** [comment]
It seems like we can punt the "implement an async API" to MediaCapabilities.

**Comment by youennf** [comment]
Closing this issue in favour of https://github.com/w3c/webrtc-extensions/issues/95
