### ISSUE TITLE
Header extension control: Unknown exception type in spec text.

### ISSUE THREAD

**Issue by handellm** [w3c/webrtc-extensions#59]
https://w3c.github.io/webrtc-extensions/#methods-0 steps 4 and 5 contains specification of IllegalArgument error types. Maybe InvalidModificationError is correct here instead? Not sure how IllegalArgument would be generated.

**Comment by alvestrand** [comment]
InvalidModificationError seems correct. I guess I did not use the proper name when writing this text.
