### ISSUE TITLE
Header extension control: spec text inconsistent with RFC5285 section 6.

### ISSUE THREAD

**Issue by handellm** [w3c/webrtc-extensions#60]
> In the algorithm for generating subsequent offers in [RTCWEB-JSEP] section 5.2.2, replace "The RTP header extensions MUST only include those that are present in the most recent answer" with "For each RTP header extension listed in [[HeaderExtensionsToOffer]] that is also present in the most recent answer, and where direction is not "stopped", generate an appropriate "a=extmap" line with "direction" set according to the rules of [RFC5285] section 6, considering the direction in [[HeaderExtensionsToOffer]] to indicate the answerer's desired usage". This preserves the property that the set of extensions may not grow with subsequent offers."

But RFC5285, section 6 says:
> A session update MAY add or remove extension(s)

Given that extmap-allow-mixed is now turning default as of https://webrtc-review.googlesource.com/c/src/+/197943, there's soon no crisis anymore with the number of header extensions in use. I propose we drop the restriction.

**Comment by handellm** [comment]
Also note https://chromium-review.googlesource.com/c/chromium/src/+/2596147.
Friendly ping :)

**Comment by alvestrand** [comment]
I think we should just do this. This extension is already modifying JSEP's language, we should modify it some more.

**Comment by juberti** [comment]
Here's some of the underlying rationale for the JSEP logic, FWIW. This particular part applies to PT selection but the same may also apply to header extension ID selection. https://github.com/rtcweb-wg/jsep/issues/266#issuecomment-275023331
