### ISSUE TITLE
fractionLost missing from MTI stats list

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-extensions#65]
I noticed that fractionLost is missing from the RTCRemoteInboundRtpStreamStats category. fractionLost reported in the RTCP Receiver Report is an important metric to exposes fraction of packets lost at the remote enduser to the local enduser. It that should be MTI.

If needed, I can make a PR.

**Comment by vr000m** [comment]
This should be addressed in the upcoming iterations, as this stat is implemented in the underlying RTCP Receiver Report (as per IETF's rtpusage doc, the report is MTI), and AFAICT the metric and RTCP RR is available within all browser implementations. The wiring to the getStats() API is missing.

The metric is highly requested because it tells the local endpoint about the fraction of packets lost for the streams that it is sending to the remote party.

**Comment by alvestrand** [comment]
I don't think fractionLost should be MTI. Due to its nature of "loss over the period since the last RR", it's fairly useless in the webrtc context. Probably easy to implement, but the information is not very useful.
