### ISSUE TITLE
Network Tokens and WebRTC QoS

### ISSUE THREAD

**Issue by yiannisy** [w3c/webrtc-extensions#68]
Hi,

--- I posted this on webrtc-qos and got redirected here by @alvestrand ---

Not sure if this is the right place, but wanted to bring into your attention network tokens (https://networktokens.org), a new project/IETF I-D that might be relevant with WebRTC and QoS.

In a nutshell: Network tokens are an open and secure method for end users and application providers to coordinate with the network about how their traffic is treated ( e.g., to access a 5G slice, a firewall whitelist, a zero-rating, or a QoS service ). Network Tokens replace complex, insecure, and privacy-invasive DPI application signatures with a deterministic and unified mechanism to build network services, and complement DSCP codepoints across network boundaries.

We have a prototype implementation using network tokens as part of WebRTC, and I'd be very interested to understand what's the best way to engage with the WebRTC group and get feedback/guidance on next steps.

**Comment by juberti** [comment]
This is an interesting proposal. In the context of a W3C API, have you thought about how said token would be supplied to the WebRTC implementation to allow it to be populated in its STUN or TURN messages?

**Comment by yiannisy** [comment]
Hi Justin,

We can pass the network token from the application to WebRTC in a similar way that ICE configuration is passed down - through an RTCConfiguration object.  We add an extra field to the configuration object within the WebRTC library, then add a networkTokens parameter when we create a new RTCPeerConnection in the application, and from there trickle it down to STUN/TURN. Eventually we insert tokens at STUN packets and verify them at the network. 

We have an initial implementation using Jitsi and WebRTC, and you can see a short demo here ( at 16:57 --> https://youtu.be/hmiDhiMyGeQ?t=1017 ) . The token  itself is user-centric and application-agnostic, and the actual access control takes place by defining how one can authenticate and fetch a token. It’s trivial to implement different options for this, e.g.,  user-centric for approved applications, user-centric and application agnostic, or application specific by using standard authentication mechanisms to fetch tokens. 

Not an expert on WebRTC by no means, so appreciate any feedback whether there a better way to do this.

**Comment by juberti** [comment]
Got it, that's what I had in mind as well. Definitely a better mechanism to classify traffic than having to whitelist IPs and ports.

**Comment by alvestrand** [comment]
I haven't seen any sign of adoption of draft-yiakoumis-network-tokens-02 in the IETF, so closing this with an "icebox" marker.
If the IETF returns to the issue, we might reopen.
