### ISSUE TITLE
ptime is mentioned but not actually settable anywhere

### ISSUE THREAD

**Issue by steely-glint** [w3c/webrtc-extensions#69]
The adaptivePtime description mentions setting ptime - but it looks like ptime got dropped from the core spec. 
It would be useful to put it back in this document.

**Comment by henbos** [comment]
ptime was not implemented, are you saying that you want ptime back because you want to be able to control ptime? Or because we are referencing something that doesn't exist?

**Comment by henbos** [comment]
Because if we don't want ptime then we could just update the adaptivePtime description

**Comment by steely-glint** [comment]
I definitely want ptime. Changing ptime to 60 reduces the packet count on a mesh call pretty significantly. It is my penultimate reason for mungeing localdescription.

**Comment by steely-glint** [comment]
Which is to say setting ptime _is_ implemented by everyone, just without a proper API.

**Comment by aboba** [comment]
Closed, based on merger of PR 94.
