### ISSUE TITLE
Add API to control WebRTC encoder, in particular to request key frame

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-extensions#72]
As show in https://github.com/w3c/webrtc-extensions/pull/37, there are use cases for more fine-grained control of encoders, in particular to trigger key frame generations.
Identified use cases
- SFrame encryption key change (related to webrtc-encoded-transform)
- Update bitrate and ask key frame request at the time of bitrate update

**Comment by youennf** [comment]
Various approaches have been identified:
- Use https://w3c.github.io/webrtc-pc/#dom-rtcrtpsendparameters-encodings or a similar approach to be able to ask for a key frame on a particular simulcast layer
- Use active=true/false as a temp workaround
- Add API in RTCRtpScriptTransformer

**Comment by aboba** [comment]
I am closing this due to merging [PR 125](https://github.com/w3c/webrtc-encoded-transform/pull/125).  Please reopen or file a new issue if there are elements that are still unresolved.
