### ISSUE TITLE
adaptivePtime prose unclear; concerns over lack of signaling

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-extensions#74]
From @nils-ohlmeier in https://github.com/mozilla/standards-positions/issues/508:

> ...  I have a couple of concerns:
> 
>   * https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-adaptiveptime says that `adaptivePtime` is a read-only parameter. That doesn't make much sense to me.
> 
>    * From https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-adaptiveptime `If adaptivePtime is set to true, ptime MUST NOT be set...` which `ptime` does this refer to? I assume `ptime` in SDP, but that should be clarified.
> 
>   * From https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-adaptiveptime `otherwise, InvalidModificationError MUST be thrown.` what means `otherwise`? If an application tries to set this to `false`? Or if the browser doesn't support this feature?
> 
>   * From looking at [w3c/webrtc-pc#2309](https://github.com/w3c/webrtc-pc/pull/2309) it appears that the agreement is to not signal this. If that is the agreement I think the spec needs stronger wording around this feature that the app is only suppose to use this if it knows that the receiver supports it. So basically we assume knowledge in the app again about supported features on the receiver side. Which is highly problematic if we consider use cases where different audio goes to different endpoints. I'm concerned that in worst case a call can start and the person on the receiver hears the audio. But when the browser decides to switch the frame rate suddenly the user won't hear anything any more. Until the browser decides to switch to something which the receiver can handle. I'm not convinced the easier and faster deployment arguments raised in the GitHub issue warrant bypassing signaling.

See also https://github.com/w3c/webrtc-extensions/issues/69 for where `ptime` went.

**Comment by jan-ivar** [comment]
@nils-ohlmeier Is this causing any known interop problems?

**Comment by jan-ivar** [comment]
> https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-adaptiveptime says that adaptivePtime is a read-only parameter. That doesn't make much sense to me.

This does indeed seem like a mistake. @henbos ?

**Comment by alvestrand** [comment]
tagging @eladalon1983 for further tagging.

**Comment by minyuel** [comment]
Hi Jan-Ivar,

Thanks for the questions! We've created a pull request to fix the first three issues. https://github.com/w3c/webrtc-extensions/pull/83

On the concern about missing signaling, a deeper discussion might be needed before we make further changes to the spec. From our current tests, we have not seen any concerning interoperability issues.

**Comment by aboba** [comment]
Closing after PR merged.
