### ISSUE TITLE
WebRTC-Extensions Implementation Status

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-extensions#80]
This issue was filed in order to track implementation of WebRTC-Extensions.  The following features are marked as "Features at Risk":

1. `getDefaultIceServers()`
2. `maxFramerate`
3. `oauth` value of `RTCIceCredentialType`
4. `RTCOAuthCredential` dictionary
5. `voiceActivityFlag`

WPT test results for WebRTC-Extensions are [here](https://wpt.fyi/results/webrtc-extensions?label=experimental&label=master&aligned), and appear to indicate: 

- `adaptivePtime`, `captureTimestamp` and `headerExtensionControl` are implemented on Chrome and Edge.
- `maxFramerate` and `playoutDelayHint` are implemented on Chrome, Edge and Safari Preview.
- `getDefaultIceServers()`, `oauth` value of `RTCIceCredentialType`, `RTCOAuthCredential` dictionary and `voiceActivityFlag` have not been implemented on any browser.

Is this accurate? 

**adaptivePtime**

Chrome Status entry is here: https://www.chromestatus.com/feature/5752004691361792
Tracking bug is here: https://bugs.chromium.org/p/chromium/issues/detail?id=1086942
"Intent to Ship" notice: https://groups.google.com/a/chromium.org/g/blink-dev/c/dsuUWMg2eSk/m/ax1EA7tlAQAJ

So it looks like `adaptivePtime` is shipping in Chrome/Edge.

**headerExtension Control**
Chrome status: https://www.chromestatus.com/feature/5680189201711104
Tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1051821
Intent to Prototype: https://groups.google.com/a/chromium.org/g/blink-dev/c/65YdUi02yZk

Based on the tracking bug, it looks like this extension has not been completely implemented: 
"Note: support for signaling directionality of header extensions in the SDP isn't implemented yet."

**maxFramerate**

Chrome/Edge implementation status of `maxFramerate` is covered here: 
https://www.chromestatus.com/feature/6216116758118400
https://bugs.chromium.org/p/chromium/issues/detail?id=857047

Neither the Chrome status entry nor the tracking bug indicate that `maxFramerate` has been implemented.  

Since [the WPT test](https://wpt.fyi/results/webrtc-extensions/RTCRtpParameters-maxFramerate.html?label=experimental&label=master&aligned) is [passing on Chrome, Edge and Safari Preview](https://wpt.fyi/results/webrtc-extensions?label=experimental&label=master&aligned). 
this leads me to wonder whether the dictionary attribute exists, but it doesn't actually do anything. 

**playoutDelayHint**

Intent to Ship: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/4W4orKqA3Rs
Chrome tracking bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=10287 (resolved as "fixed")
Firefox tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1585009 (resolved as "fixed")

Looks like this has been implemented on Chrome, Edge, FF and Safari Preview. 
FF WPT test is [MISSING](https://wpt.fyi/results/webrtc-extensions/RTCRtpReceiver-playoutDelayHint.html?label=experimental&label=master&aligned), due to a WPT issue?

**Comment by alvestrand** [comment]
maxFramerate is shipped in Chrome.

**Comment by jan-ivar** [comment]
> Looks like this has been implemented on Chrome, Edge, FF and Safari Preview. 
>FF WPT test is [MISSING](https://wpt.fyi/results/webrtc-extensions/RTCRtpReceiver-

@aboba Firefox has not implemented `playoutDelayHint` AFAIK. I don't know why some of those tests are passing, but they're buggy if they do.

**Comment by youennf** [comment]
There is some interest in Safari for maxFrameRate and voiceActivityFlag.
None for getDefaultIceServers, oauth and RTCOAuthCredential.

**Comment by aboba** [comment]
Looks like we could use a test that `maxFramerate` actually does something. Fippo wrote one: 
https://chromium-review.googlesource.com/c/chromium/src/+/2228552

Can we get this checked into WPT?

**Comment by alvestrand** [comment]
I'm a reviewer on that CL, and fippo hasn't answered my comment on it, so it's pending....

**Comment by aboba** [comment]
Closing, as the latest Editor's Draft has updated the entries for "feature at risk".
