### ISSUE TITLE
Should RtcRtpHeaderExtensionCapabilities offer an "enabled" member?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-extensions#99]
Current text on RTCRtpHeaderExtensionCapabilities says that each entry contains only the URL.
The default header extensions to offer is constructed by this text:

"Let [[HeaderExtensionsToOffer]] be an internal slot of the [RTCRtpTransceiver](https://www.w3.org/TR/webrtc/#dom-rtcrtptransceiver), initialized to the platform-specific list of implemented RTP header extensions. The [direction](https://w3c.github.io/webrtc-extensions/#dom-rtcrtpheaderextensioncapability-direction) attribute for all extensions that are mandatory to use MUST be initialized to an appropriate value other than "[stopped](https://www.w3.org/TR/webrtc/#dom-rtcrtptransceiverdirection-stopped)". The direction attribute for extensions that will not be offered by default in an initial offer MUST be initialized to "stopped"."

This doesn't seem to offer the option of figuring out what header extensions can be set.
Suggestion: Add a string "defaultDirection" to the RTCRtpHeaderExtensionCapabilities, and modify the text quoted above to say "initialized to the value of [[defaultHeaderExtensionCapabilities]]" with "direction" set to "defaultDirection".

If we don't modify capabilities, there seems to be an inconsistency between capabilities as returned by "getCapabilities" and the information returned by creating a Transceiver and querying its HeaderExtensionsToOffer parameter.

**Comment by fippo** [comment]
I think it does -- Chrome just happens to filter "stopped" extensions [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/media/base/media_engine.cc;l=62;drc=a2d4701bea545269ad3f5fe6e111adb65c46b8da9) which is not what the spec says.

Does setOfferedHeaderExtensions filter those by default or do we need to modify the algorithm to do so?

**Comment by fippo** [comment]
If we do that, do we also have getSenders/getReceivers return codecs that are not enabled by default and must be explicitly turned on via setCodecPreferences?

**Comment by aboba** [comment]
Proposed resolution at the March 15, 2022 Virtual Interim (https://www.w3.org/2022/03/15-webrtc-minutes.html): Close with no change.

**Comment by alvestrand** [comment]
I had a different reading of the sense of the room; I thought I heard support for leaving out the feature until demand is found.

**Comment by alvestrand** [comment]
Closing as directed.
